### ISSUE TITLE
播放延迟问题

### ISSUE THREAD

**Issue by lisheng1992** [wobiancao/RtspServerAndVlcPlay#2]
你好，我用libstreaming发送RTSP流，直接连接wifi热点，用这个播放，发现有2秒的延迟，在PC上用VLC播放只有500ms的延迟，请问怎么设置网络延迟参数了，在网上搜到设置network-caching=300，发现没多大作用啊，请大神帮忙看下这个问题

**Comment by mehao** [comment]
一样遇到这个问题，延迟太大了，根本没法用，效果太差了

**Comment by wobiancao** [comment]
我只是用了一下demo实现。 真正情况下是没法用的 1是设备性能问题 2是网络延迟丢帧问题
这两个问题 可以去底层优化 我这个只是做个演示用 能满足我的需求 可能没法满足你们的

**Comment by Marx-Hong** [comment]
代码为啥跟别人的一模一样，连bug的回复都一模一样，在下佩服

**Comment by wobiancao** [comment]
> 代码为啥跟别人的一模一样，连bug的回复都一模一样，在下佩服

?

**Comment by wobiancao** [comment]
> 代码为啥跟别人的一模一样，连bug的回复都一模一样，在下佩服

**重点声明: rtsplibrary是基于libstreaming开源封装 libvlc-android是别人开源vlc项目编译好的，非本人编译**
麻烦你眼睛擦亮点，这位朋友。

**Comment by SubinVane** [comment]
全局搜索network-caching，设置低延时亲测有效
